### ISSUE TITLE
Community page: 404 page not found

### ISSUE THREAD

**Issue by platonenkoiurii** [magma/magma-website#143]
The community page is not available: https://magmacore.org/community

I can't find a direct link to it from https://magmacore.org
I have navigated to it through https://docs.magmacore.org and the "Community" in the top right 

As I'm not sure about the overall collaboration strategy, I can see several possible actions:
- remove "Community" from https://docs.magmacore.org
- add a link to Slack?

best regards

**Comment by Neudrino** [comment]
This issue was resolved with https://github.com/magma/magma/pull/13166.
Could you close it please @magma/repo-magma-website-write .
