### ISSUE TITLE
[DOC] Documentation is pointing to old github.io that redirect to engineering.fb.com

### ISSUE THREAD

**Issue by tmdzk** [magma/magma-website#4]
# Bug report

Documentation links are pointing to old facebookincubator.github.io (that is now down and redirect to engineering.fb.com)

**If the current behavior is a bug, please provide the steps to reproduce.**

Hit docs links

**What is the expected behavior?**

redirect to magma.github.io

**Other relevant information:**

**Comment by tmdzk** [comment]
https://github.com/magma/magma-website/pull/5

I can't link the issue to my PR but here it is.

**Comment by jbryce** [comment]
PR merged and fix deployed
